"use client";

import {
  Home as LuHome,
  Map as LuMap,
  List as LuList,
  ArrowLeftRight as LuExchange,
  Bell as LuBell,
  Users as LuUsers,
  User as LuUser,
  Building2 as LuBuilding,
  BarChart3 as LuChart,
  Droplet as LuLiquid,
  FileText as LuDoc,
  Settings as LuCog,
  Mail as LuMail,
  Lock as LuLock,
  Eye as LuEye,
  EyeOff as LuEyeOff,
  Search as LuSearch,
  ArrowRight as LuArrow,
  ChevronDown as LuChevron,
  ChevronRight as LuChevronR,
  ChevronLeft as LuChevronL,
  Download as LuDownload,
  Printer as LuPrint,
  Calendar as LuCalendar,
  Filter as LuFilter,
  Phone as LuPhone,
  X as LuX,
  Plus as LuPlus,
  Check as LuCheck,
  AlertTriangle as LuAlert,
  LogOut as LuLogout,
  Shield as LuShield,
  SlidersHorizontal as LuSettings,
  ArrowUp as LuArrowUp,
  ArrowDown as LuArrowDown,
  RefreshCw as LuRefresh,
  Maximize as LuFullscreen,
  Star as LuStar,
  Camera as LuCamera,
  Save as LuSave,
  Trash2 as LuTrash,
  Upload as LuUpload,
  Sparkles as LuSpark,
  Trophy as LuTrophy,
  Medal as LuMedal,
} from "lucide-react";

export const Ic = {
  Home:       () => <LuHome      size={16} strokeWidth={1.6} />,
  Map:        () => <LuMap       size={16} strokeWidth={1.6} />,
  List:       () => <LuList      size={16} strokeWidth={1.6} />,
  Exchange:   () => <LuExchange  size={16} strokeWidth={1.6} />,
  Bell:       () => <LuBell      size={16} strokeWidth={1.6} />,
  Users:      () => <LuUsers     size={16} strokeWidth={1.6} />,
  User:       () => <LuUser      size={16} strokeWidth={1.6} />,
  Building:   () => <LuBuilding  size={16} strokeWidth={1.6} />,
  Chart:      () => <LuChart     size={16} strokeWidth={1.6} />,
  Liquid:     () => <LuLiquid    size={16} strokeWidth={1.6} />,
  Doc:        () => <LuDoc       size={16} strokeWidth={1.6} />,
  Cog:        () => <LuCog       size={16} strokeWidth={1.6} />,
  Mail:       () => <LuMail      size={16} strokeWidth={1.6} />,
  Lock:       () => <LuLock      size={16} strokeWidth={1.6} />,
  Eye:        () => <LuEye       size={16} strokeWidth={1.6} />,
  EyeOff:     () => <LuEyeOff    size={16} strokeWidth={1.6} />,
  Search:     () => <LuSearch    size={16} strokeWidth={1.6} />,
  Arrow:      () => <LuArrow     size={14} strokeWidth={2}   />,
  Chevron:    () => <LuChevron   size={12} strokeWidth={2}   />,
  ChevronR:   () => <LuChevronR  size={12} strokeWidth={2}   />,
  ChevronL:   () => <LuChevronL  size={12} strokeWidth={2}   />,
  Download:   () => <LuDownload  size={14} strokeWidth={1.6} />,
  Print:      () => <LuPrint     size={14} strokeWidth={1.6} />,
  Calendar:   () => <LuCalendar  size={14} strokeWidth={1.6} />,
  Filter:     () => <LuFilter    size={14} strokeWidth={1.6} />,
  Phone:      () => <LuPhone     size={14} strokeWidth={1.6} />,
  X:          () => <LuX         size={16} strokeWidth={2}   />,
  Plus:       () => <LuPlus      size={14} strokeWidth={2}   />,
  Check:      () => <LuCheck     size={14} strokeWidth={2}   />,
  Alert:      () => <LuAlert     size={16} strokeWidth={1.6} />,
  Logout:     () => <LuLogout    size={14} strokeWidth={1.6} />,
  Shield:     () => <LuShield    size={14} strokeWidth={1.6} />,
  Settings:   () => <LuSettings  size={14} strokeWidth={1.6} />,
  ArrowUp:    () => <LuArrowUp   size={14} strokeWidth={2}   />,
  ArrowDown:  () => <LuArrowDown size={14} strokeWidth={2}   />,
  Refresh:    () => <LuRefresh   size={14} strokeWidth={1.6} />,
  Fullscreen: () => <LuFullscreen size={14} strokeWidth={1.6} />,
  Star: ({ filled = true }: { filled?: boolean }) => (
    <LuStar size={13} strokeWidth={1.4} fill={filled ? "currentColor" : "none"} />
  ),
  Camera: () => <LuCamera size={14} strokeWidth={1.6} />,
  Save:   () => <LuSave   size={14} strokeWidth={1.6} />,
  Trash:  () => <LuTrash  size={14} strokeWidth={1.6} />,
  Upload: () => <LuUpload size={14} strokeWidth={1.6} />,
  Spark:  () => <LuSpark  size={14} strokeWidth={1.6} />,
  Trophy: () => <LuTrophy size={14} strokeWidth={1.6} />,
  Medal:  () => <LuMedal  size={14} strokeWidth={1.6} />,
};

export type IcKey = keyof typeof Ic;
